"""empty message

Revision ID: 8cdfbe08ceea
Revises: 233c3d5f1f95
Create Date: 2024-02-18 14:55:36.841891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdfbe08ceea'
down_revision = '233c3d5f1f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.drop_column('looking_talent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
